# For a quick start check out our HTTP Requests collection
# (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form
# with a text or file field (multipart/form-data);

#
### User Registration
#

POST http://localhost:3000/api/user/create
Content-Type: application/json

{
  "first": "first name",
  "last": "last name",
  "email": "test@mail.com",
  "password": "12345678aA",
  "locale": "ru"
}

###

GET http://localhost:3000/api/user/check-email?email=test@mail.com
Accept: application/json

###

POST http://localhost:3000/api/user/activate
Content-Type: application/json

{
  "email": "test@mail.com",
  "token": "dvfdmf3g8blmhbv0"
}

#
###  User Reset Password
#

POST http://localhost:3000/api/user/password/token-generate
Content-Type: application/json

{
  "email": "test@mail.com"
}

###

GET http://localhost:3000/api/user/password/token-check?email=test@mail.com&token=wy7vjyoz5fr8co0m
Accept: application/json

###

POST http://localhost:3000/api/user/password/change
Content-Type: application/json

{
  "email": "test@mail.com",
  "password": "123456aA",
  "token": "wy7vjyoz5fr8co0m"
}

###
