# For a quick start check out our HTTP Requests collection
# (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form
# with a text or file field (multipart/form-data);

###

PUT http://localhost:3000/api/user/change/locale
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjViZmE5ODFhZTc3NDExZDA4MjhiYzE3NyIsImlhdCI6MTU0MzI0NjUwMX0.EwyKIdcBCLAbmSgLdjMeeN8WOXUrqBGah4f1oPQC_dU

{
  "locale": "ru"
}

###

PUT http://localhost:3000/api/user/change/image
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjViZmE5ODFhZTc3NDExZDA4MjhiYzE3NyIsImlhdCI6MTU0MzI0NjUwMX0.EwyKIdcBCLAbmSgLdjMeeN8WOXUrqBGah4f1oPQC_dU

{
  "image": "image.png"
}

###

PUT http://localhost:3000/api/user/change/email
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjViZmE5ODFhZTc3NDExZDA4MjhiYzE3NyIsImlhdCI6MTU0MzI0NjUwMX0.EwyKIdcBCLAbmSgLdjMeeN8WOXUrqBGah4f1oPQC_dU

{
  "email": "jeliy@rsvhr.com",
  "password": "123qweAA"
}

###

PUT http://localhost:3000/api/user/change/data
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjViZmE5ODFhZTc3NDExZDA4MjhiYzE3NyIsImlhdCI6MTU0MzI0NjUwMX0.EwyKIdcBCLAbmSgLdjMeeN8WOXUrqBGah4f1oPQC_dU

{
  "first": "John",
  "last": "Smith",
  "oldPassword": "123qweAA",
  "newPassword": "123qweAB"
}

###
