version: '3'

services:
  mailhog:
        image: mailhog/mailhog:v1.0.0
        container_name: mailhog
        restart: always
        ports:
          - "1025:1025"
          - "8025:8025"
  nginx:
      image: nginx:1.13
      container_name: nginx
      volumes:
          - ../nginx/nginx.conf:/etc/nginx/nginx.conf
          - /:/var/www/html
      ports:
          - "8013:8013"